app.name = backoffice
app.version = 1.0.0
app.env = development

view.prefix = /WEB-INF/views/
view.suffix = .jsp

db.driver = org.postgresql.Driver
db.url = jdbc:postgresql://localhost:5432/backoffice_db
db.username = postgres
db.password = monmotdepasse